aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
    windev: sudo mount.cifs -o rw,user=bryan,uid=$(id -u),gid=$(id -g),forceuid,forcegid,vers=3.0 //192.168.122.69/bowtie /mnt/windev
allow_broken: false
auto_gc: true
bling: default
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - unison
    - chezmoi
    - bitwarden
    - bitwarden-cli
    - emacs
    - xclip
    - patch
    - kubectl
    - devbox
    - simple-scan
    - synergy
    - wireshark
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      home: ""
      hostname: blofeld
      os: linux
      user:
        email: bryan@larsen.st
        name: Bryan Larsen
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: blarsen
      username: blarsen
track: nixos-unstable
unfree: true
users: []
